<!--?php
defined('_JEXEC') or die;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
JLoader::register('fieldattach', 'components/com_fieldsattach/helpers/fieldattach.php');
JHtml::_('behavior.caption');
?-->
<?php
defined('_JEXEC') or die;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
JLoader::register('fieldattach', 'components/com_fieldsattach/helpers/fieldattach.php');
// Create shortcuts to some parameters.
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);
JHtml::_('behavior.caption');
?>
<?$fields = fieldattach::getArrayValue($this->item->id,$category = false);?>
<?$imgs = fieldattach::getGalleryArrayValue(8,$this->item->id,$category = false);?>
<?$image = json_decode($this->item->images, true);?>
<?$link = JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>
<?$i=0;?>
<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<?php if ($this->params->get('show_page_heading')) : ?>

<div class="page-header">

	<?php endif;
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
	{
		echo $this->item->pagination;
	}
	?>


	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php if (!$params->get('show_intro')) : echo $this->item->event->afterDisplayTitle; endif; ?>
	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>

	
	
    <h1><?php echo $this->escape($this->item->title); ?>  </h1>


<?foreach($imgs as $img):?>
    <?if($i==0):?><div class="row apartament-imgs"><?endif;?>
    <div class="col-md-4"><a href="<?=$img['image1']?>" class="lightbox"><img src="<?=$img['image1']?>" class="img-responsive" alt="" /></a></div>
    <?$i++;if($i==3):?></div><?$i=0;?><?endif;?>
<?endforeach;?>
<?if($i==2):?><div class="col-md-4"></div></div>
<?endif;?>
<?if($i==1):?><div class="col-md-4"></div><div class="col-md-4"></div>
<?endif;?>

<br>

<div class="row apartament">
    <div class="col-md-1"><img src="/templates/mkot/img/room-list-gallery__info-icon.svg" alt="" /></div>
    <div class="col-md-11">
        <?php echo $this->item->text; ?>
    </div>
	
	
	
<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	
<?php echo $this->item->event->afterDisplayContent; ?></div>