<?php
defined('_JEXEC') or die;
JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');
JLoader::register('fieldattach', 'components/com_fieldsattach/helpers/fieldattach.php');
// Create shortcuts to some parameters.
$params  = $this->item->params;
$images  = json_decode($this->item->images);
$urls    = json_decode($this->item->urls);
$canEdit = $params->get('access-edit');
$user    = JFactory::getUser();
$info    = $params->get('info_block_position', 0);
JHtml::_('behavior.caption');
?>

<?$fields = fieldattach::getArrayValue($this->item->id,$category = false);?>
<?$imgs = fieldattach::getGalleryArrayValue(7,$this->item->id,$category = false);?>
<?$image = json_decode($this->item->images, true);?>
<?$link = JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>

<div class="item-page<?php echo $this->pageclass_sfx; ?>" itemscope itemtype="https://schema.org/Article">
	<meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? JFactory::getConfig()->get('language') : $this->item->language; ?>" />
	<?php if ($this->params->get('show_page_heading')) : ?>

<div class="page-header">
    

	<?php endif;
	if (!empty($this->item->pagination) && $this->item->pagination && !$this->item->paginationposition && $this->item->paginationrelative)
	{
		echo $this->item->pagination;
	}
	?>


	<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
	<?php if (!$params->get('show_intro')) : echo $this->item->event->afterDisplayTitle; endif; ?>
	<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
	<?php echo $this->item->event->beforeDisplayContent; ?>

	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>

	<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && !$this->item->paginationrelative):
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	<?php if (isset ($this->item->toc)) :
		echo $this->item->toc;
	endif; ?>
	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '1')) || ($params->get('urls_position') == '1'))) : ?>
	<?php echo $this->loadTemplate('links'); ?>
	<?php endif; ?>
	<h1><?php echo $this->escape($this->item->title); ?>  </h1>
<div class="row masters">
<div class="col-md-12">
    <div class="row">
        <div class="col-md-4">
            <a href="<?=$image['image_intro']?>" class="lightbox"><img src="<?=$image['image_intro']?>" class="img-responsive" alt="" /></a>
            <ul class="master-small-img">
            <?foreach($imgs as $small_img):?>
                <li>
                    <a href="<?=$small_img['image1']?>" class="lightbox" rel="gallery<?=$this->item->id?>">
                        <img src="<?=$small_img['image1']?>" class="img-responsive" width="80" alt="" />
                    </a>
                </li>
            <?endforeach;?>
            </ul>
        </div>
		<div itemprop="articleBody">
        <div class="col-md-4 masters-short-descr" style="padding-top:70px">
           <?php echo $this->item->introtext; ?>
        </div>
        <div class="col-md-4 masters-full-descr"><?php echo $this->item->fulltext; ?></div>
    </div>
</div>
</div></div>

<?php
	if (!empty($this->item->pagination) && $this->item->pagination && $this->item->paginationposition && $this->item->paginationrelative) :
		echo $this->item->pagination;
	?>
	<?php endif; ?>
	
<?php echo $this->item->event->afterDisplayContent; ?></div>